version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge